export const GET_AMBASSADOR_BY_ID_REQUEST = 'GET_AMBASSADOR_BY_ID_REQUEST'
export const GET_AMBASSADOR_BY_ID_SUCCESS = 'GET_AMBASSADOR_BY__ID_SUCCESS'
export const GET_AMBASSADOR_BY_ID_FAIL = 'GET_AMBASSADOR_BY_ID_FAIL'

export const GET_AMBASSADORS_LIST_REQUEST = 'GET_AMBASSADORS_LIST_REQUEST'
export const GET_AMBASSADORS_LIST_SUCCESS = 'GET_AMBASSADORS_LIST_SUCCESS'
export const GET_AMBASSADORS_LIST_FAIL = 'GET_AMBASSADORS_LIST_FAIL'

export const GET_AMBASSADORS_REQUEST = 'GET_AMBASSADORS_REQUEST'
export const GET_AMBASSADORS_SUCCESS = 'GET_AMBASSADORS_SUCCESS'
export const GET_AMBASSADORS_FAIL = 'GET_AMBASSADORS_FAIL'

export const SET_FILTER = 'SET_FILTER'
export const CLEAR_FILTER = 'CLEAR_FILTER'