export const AUTH = 'AUTH'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST'
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS'
export const SIGN_UP_USER_FAIL = 'SIGN_UP_USER_FAIL'

export const SET_EMAIL_REQUEST = 'SET_EMAIL_REQUEST'
export const SET_EMAIL_SUCCESS = 'SET_EMAIL_SUCCESS'
export const SET_EMAIL_FAIL = 'SET_EMAIL_FAIL'

export const GET_PASSWORD_CONFIRM_REQUEST = 'GET_PASSWORD_CONFIRM_REQUEST'
export const GET_PASSWORD_CONFIRM_SUCCESS = 'GET_PASSWORD_CONFIRM_SUCCESS'
export const GET_PASSWORD_CONFIRM_FAIL = 'GET_PASSWORD_CONFIRM_FAIL'

export const RESET_PASSWORD_CONFIRM_REQUEST = 'RESET_PASSWORD_CONFIRM_REQUEST'
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORDCONFIRM_SUCCESS'
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRMFAIL'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'

export const GET_EMAIL_CONFIRM_REQUEST = 'GET_EMAIL_CONFIRM_REQUEST'
export const GET_EMAIL_CONFIRM_SUCCESS = 'GET_EMAIL_CONFIRM_SUCCESS'
export const GET_EMAIL_CONFIRM_FAIL = 'GET_EMAIL_CONFIRM_FAIL'

export const SET_VERIFY_EMAIL_REQUEST = 'SET_VERIFY_EMAIL_REQUEST'
export const SET_VERIFY_EMAIL_SUCCESS = 'SET_VERIFY_EMAIL_SUCCESS'
export const SET_VERIFY_EMAIL_FAIL = 'SET_VERIFY_EMAIL_FAIL'

export const LOGIN_USER_INIT_REQUEST = 'LOGIN_USER_INIT_REQUEST'
export const LOGIN_USER_INIT_SUCCESS = 'LOGIN_USER_INIT_SUCCESS'
export const LOGIN_USER_INIT_FAIL = 'LOGIN_USER_INIT_FAIL'

export const LOGOUT = 'LOGOUT'
