export const SEND_MESSAGE = 'SEND_MESSAGE'
export const GET_MESSAGE = 'GET_MESSAGE'

export const GET_SOCKET_CONTACT_LIST = 'GET_SOCKET_CONTACT_LIST'
export const GET_SOCKET_MESSAGE_SENT = 'GET_SOCKET_MESSAGE_SENT'
export const GET_SOCKET_MESSAGE_SEEN = 'GET_SOCKET_MESSAGE_SEEN'

export const GET_MESSAGE_HISTORY_REQUEST = 'GET_MESSAGE_HISTORY_REQUEST'
export const GET_MESSAGE_HISTORY_SUCCESS = 'GET_MESSAGE_HISTORY_SUCCESS'
export const GET_MESSAGE_HISTORY_FAIL = 'GET_MESSAGE_HISTORY_FAIL'

export const GET_FAVORITES_CONTACT_REQUEST = 'GET_FAVORITES_CONTACT_REQUEST'
export const GET_FAVORITES_CONTACT_SUCCESS = 'GET_FAVORITES_CONTACT_SUCCESS'
export const GET_FAVORITES_CONTACT_FAIL = 'GET_FAVORITES_CONTACT_FAIL'

export const ADD_TO_FAVORITES_REQUEST = 'ADD_TO_FAVORITES_REQUEST'
export const ADD_TO_FAVORITES_SUCCESS = 'ADD_TO_FAVORITES_SUCCESS'
export const ADD_TO_FAVORITES_FAIL = 'ADD_TO_FAVORITES_FAIL'

export const REMOVE_FAVORITE_CONTACT_REQUEST = 'REMOVE_FAVORITE_CONTACT_REQUEST'
export const REMOVE_FAVORITE_CONTACT_SUCCESS = 'REMOVE_FAVORITE_CONTACT_SUCCESS'
export const REMOVE_FAVORITE_CONTACT_FAIL = 'REMOVE_FAVORITE_CONTACT_FAIL'

export const REMOVE_CONTACT_REQUEST = 'REMOVE_CONTACT_REQUEST'
export const REMOVE_CONTACT_SUCCESS = 'REMOVE_CONTACT_SUCCESS'
export const REMOVE_CONTACT_FAIL = 'REMOVE_CONTACT_FAIL'

export const ADD_TO_CONTACT = 'ADD_TO_CONTACT'

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES'

export const ADD_SOCKET_TO_CONTACT = 'ADD_SOCKET_TO_CONTACT'

export const ADD_SOCKET_TYPING_START = 'ADD_SOCKET_TYPING_START'
export const ADD_SOCKET_TYPING_END = 'ADD_SOCKET_TYPING_END'

export const SET_CURR_CONTACT = 'SET_CURR_CONTACT'

export const REMOVE_CONTACT = 'REMOVE_CONTACT'
export const REMOVE_FAVORITE_CONTACT = 'REMOVE_FAVORITE_CONTACT'

