export const GET_NEWS_REQUEST = 'GET_NEWS_REQUEST'
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS'
export const GET_NEWS_FAIL = 'GET_NEWS_FAIL'

export const GET_NEWS_BY_ID_REQUEST = 'GET_NEWS_BY_ID_REQUEST'
export const GET_NEWS_BY_ID_SUCCESS = 'GET_NEWS_BY_ID_SUCCESS'
export const GET_NEWS_BY_ID_FAIL = 'GET_NEWS_BY_ID_FAIL'