export const IMG_UPLOAD_REQUEST = 'IMG_UPLOAD_REQUEST'
export const IMG_UPLOAD_SUCCESS = 'IMG_UPLOAD_SUCCESS'
export const IMG_UPLOAD_FAIL = 'IMG_UPLOAD_FAIL'

export const VIDEO_UPLOAD_REQUEST = 'VIDEO_UPLOAD_REQUEST'
export const VIDEO_UPLOAD_SUCCESS = 'VIDEO_UPLOAD_SUCCESS'
export const VIDEO_UPLOAD_FAIL = 'VIDEO_UPLOAD_FAIL'

export const GET_SIMILAR_USERS_REQUEST = 'GET_SIMILAR_USERS_REQUEST'
export const GET_SIMILAR_USERS_SUCCESS = 'GET_SIMILAR_USERS_SUCCESS'
export const GET_SIMILAR_USERS_FAIL = 'GET_SIMILAR_USERS_FAIL'

export const GET_ALL_TOPICS_REQUEST = 'GET_ALL_TOPICS_REQUEST'
export const GET_ALL_TOPICS_SUCCESS = 'GET_ALL_TOPICS_SUCCESS'
export const GET_ALL_TOPICS_FAIL = 'GET_ALL_TOPICS_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const UPDATE_USE_NOTIFICATION_REQUEST = 'UPDATE_USE_NOTIFICATION_REQUEST'
export const UPDATE_USER_NOTIFICATION_SUCCESS = 'UPDATE_USER_NOTIFICATION_SUCCESS'
export const UPDATE_USER_NOTIFICATION_FAIL = 'UPDATE_USER_NOTIFICATION_FAIL'

export const UPDATE_USER_EMAIL_REQUEST = 'UPDATE_USER_EMAIL_REQUEST'
export const UPDATE_USER_EMAIL_SUCCESS = 'UPDATE_USER_EMAIL_SUCCESS'
export const UPDATE_USER_EMAIL_FAIL = 'UPDATE_USER_EMAIL_FAIL'

export const UPLOAD_USER_PROFILE_VIDEO_REQUEST = 'UPLOAD_USER_PROFILE_VIDEO_REQUEST'
export const UPLOAD_USER_PROFILE_VIDEO_SUCCESS = 'UPLOAD_USER_PROFILE_VIDEO_SUCCESS'
export const UPLOAD_USER_PROFILE_VIDEO_FAIL = 'UPLOAD_USER_PROFILE_VIDEO_FAIL'

export const UPDATE_USER_PROFILE_VIDEO_REQUEST = 'UPDATE_USER_PROFILE_VIDEO_REQUEST'
export const UPDATE_USER_PROFILE_VIDEO_SUCCESS = 'UPDATE_USER_PROFILE_VIDEO_SUCCESS'
export const UPDATE_USER_PROFILE_VIDEO_FAIL = 'UPDATE_USER_PROFILE_VIDEO_FAIL'

export const UPDATE_USER_PROFILE_IMG_REQUEST = 'UPDATE_USER_PROFILE_IMG_REQUEST'
export const UPDATE_USER_PROFILE_IMG_SUCCESS = 'UPDATE_USER_PROFILE_IMG_SUCCESS'
export const UPDATE_USER_PROFILE_IMG_FAIL = 'UPDATE_USER_PROFILE_IMG_FAIL'

export const UPDATE_USER_PASSWORD_REQUEST = 'UPDATE_USER_PASSWORD_REQUEST'
export const UPDATE_USER_PASSWORD_SUCCESS = 'UPDATE_USER_PASSWORD_SUCCESS'
export const UPDATE_USER_PASSWORD_FAIL = 'UPDATE_USER_PASSWORD_FAIL'


export const DELETE_TAG_REQUEST = 'DELETE_TAG_REQUEST'
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS'
export const DELETE_TAG_FAIL = 'DELETE_TAG_FAIL'

export const ADD_TOPIC_REQUEST = 'ADD_TOPIC_REQUEST'
export const ADD_TOPIC_SUCCESS = 'ADD_TOPIC_SUCCESS'
export const ADD_TOPIC_FAIL = 'ADD_TOPIC_FAIL'

export const ADD_REVIEWS_REQUEST = 'ADD_REVIEWS_REQUEST'
export const ADD_REVIEWS_SUCCESS = 'ADD_REVIEWS_SUCCESS'
export const ADD_REVIEWS_FAIL = 'ADD_REVIEWS_FAIL'

export const CLEAR_DATA = 'CLEAR_DATA'
